Hass does not have a time function so Use Python Time
This should correct this warning that occurs every 15 minutes in the Home Assistant Logs. Please verify if this is correct though and is in allignment with your code.   This error originated from a custom integration.

Logger: custom_components.control_my_spa.select.temperature
Source: custom_components/control_my_spa/select/temperature.py:107
integration: Balboa SPA (documentation)
First occurred: March 1, 2026 at 7:37:42 PM (2 occurrences)
Last logged: 4:50:34 PM

Error comparing temperatures: 'HomeAssistant' object has no attribute 'time'